### ISSUE TITLE
Mutation testing for Dart?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [theofidry/awesome-mutation-testing#49]
Does anyone know if there is a library to do mutation testing in Dart?

**Comment by theofidry** [comment]
Not that I'm aware unfortunately. If you do find one however, please submit a PR to add it! Otherwise I think the best candidate for adding support to it is likely to be Stryker since it already supports JS and TypeScript

**Comment by MelbourneDeveloper** [comment]
I asked the Stryker team and apparently no plans for flutter right now.

Here is an article:
https://flutterfromdotnet.hashnode.dev/mutation-testing

Sorry that it won't help you much.

@HerrNiklasRaab @theofidry
