### ISSUE TITLE
Slack invitation link broken

### ISSUE THREAD

**Issue by liyishuai** [theofidry/awesome-mutation-testing#53]
https://mutation-testing-slack.herokuapp.com/

> No such app

**Comment by mbj** [comment]
@liyishuai This is because the slack was discontinued, the mutation testing community was moved to discord, see: https://twitter.com/_m_b_j_/status/1340440401849815041

Discord is more friendly a medium for communities than slack.

**Comment by theofidry** [comment]
@mbj any chance to have a permanent link that we could use here?

**Comment by mbj** [comment]
@theofidry The one from mutants README and the tweet are permanent ones.

**Comment by theofidry** [comment]
Updated

**Comment by mbj** [comment]
@theofidry thx! BTW the discord is in the ~4w we had so far more active in sum than the Slack ever was.
